version: "2"

services:

  api:
    build: .
    container_name: api
    environment:
      DATABASE_URL: "sqlite:///db.sqlite"
      DEBUG: "False"
    volumes:
      - ./db.sqlite:/code/db.sqlite
    ports:
      - "8001:8001"